### ISSUE TITLE
Documentation for the front-end and back-end structuring for reference.

### ISSUE THREAD

**Issue by FarahZaqout** [ashatat/e-commerce#10]
# Detail the front-end views and back-end API for reference.
@ashatat @amusameh @RamyAlshurafa what do you think?
## Front End:
* [ ] Landing Page
* [ ] Shop
* [ ] Cart
* [ ] Item View
* [ ] Wish list
* [ ] Login and Signup

### What we should include in the details:
* all parts of the page (each should has its own issue)
* what kind of information should this page receive? (probably better detailed under the specific issue of the part that receives/sends the information to the backend API).
* on each part of the page, we should relate it to the public component issue if applicable.

## Back End:
* [ ] CRUD queries
* [ ] Endpoints API
* [ ] Database Schema

### CRUD queries:
* List all queries for the website
* Each query should have its own issue, detailing what specific data it sends/retrieves from the database

### Endpoints API:
* List all endpoints
* each endpoint should have its own issue, detailing the methods it should deal with, the CRUD queries it should call, the possible scenarios it could go through (success, failure, redirect...etc.) with the proper status codes, data, and error messages...etc.

## Database Schema:
* List of all the table
* Picture of the Database schema depicting all tables and relations between them.

**Comment by ashatat** [comment]
I think this is a good documentation
but I didn't get this part
>on each part of the page, we should relate it to the public component issue if applicable.

@FarahZaqout

**Comment by amusameh** [comment]
I think the (header, footer, and sideNavBar) should be separate, maybe grouped in a main layout epic!

**Comment by FarahZaqout** [comment]
@ashatat The reusable components is what I mean by public components. So we should create an issue that lists all of them. And the way it works is whenever you are working on a component, if it's going to be used again, it should be related inside the public/reusable component issue.

This would take us a lot of experimentation. We'll get a good sense of how to best do it as we progress in the project.

**Comment by FarahZaqout** [comment]
@amusameh That's definitely a great idea. You should do that.

**Comment by amusameh** [comment]
I agree with this. We should be starting with the database schema and keep detailing the issues as we progress and things become more clear.
