### ISSUE TITLE
Agree to the best file structure to go with for components.

### ISSUE THREAD

**Issue by FarahZaqout** [ashatat/e-commerce#34]
Should be over by the end of tomorrow.

**Comment by FarahZaqout** [comment]
# - src
##  -- components
   **-- common**
    **-- stateful**
    **-- stateless**
 
  **-- pages**

**Comment by RamyAlshurafa** [comment]
I recommend this Link
https://reactjs.org/docs/faq-structure.html

**Comment by ashatat** [comment]
`If you’re just starting a project, don’t spend more than five minutes on choosing a file structure. `
Check this [link](https://reactjs.org/docs/faq-structure.html)

I think of having two main folders like this:
```
- components
  |__ // here goes the components that we don't call it in the router
- Pages
  |__// here goes the pages components which we will call it at the router
```

**Comment by amusameh** [comment]
Are we going to use redux?

**Comment by ashatat** [comment]
I agree with what @FarahZaqout  said, but I am not sure about separating to `stateless` and `stateful` is a good idea
what do you think guys?

@amusameh , my opinion is to use redux, but only when we need it ((when the state get complicated))

**Comment by FarahZaqout** [comment]
Alright, we will be using the first method specified in react docs.
