### ISSUE TITLE
wishlist item component

### ISSUE THREAD

**Issue by RamyAlshurafa** [ashatat/e-commerce#49]
Relates #7 
you can find it [here](http://atelier.swiftideas.com/wishlist/view/)
![screenshot from 2018-10-22 00-05-13](https://user-images.githubusercontent.com/34629478/47272422-2ce3d080-d58e-11e8-9805-3bdd86a6d59a.png)

### Acceptance criteria:

- [ ] Component name: `WishlistItem`.

- [ ] component props : 
   ```js
   id:6,
   imgUrl: 'link',
   name: 'string',
   price: 290,
   isInStock: boolean,
   addToCart: function,
   removeFromList: function
   ```

- [ ]  component callcback events :

   ```js
   addTocart(id),
   removeFromList(id)
   ```

- [ ] Component should be stateless component

**Comment by FarahZaqout** [comment]
Turns out rendering arrow functions merits a stateful class component use over a stateless function component.
