### ISSUE TITLE
Agreeing on a naming convention for html class names

### ISSUE THREAD

**Issue by amusameh** [ashatat/e-commerce#53]
I think we should agree on a naming convention for HTML classes.
Maybe using BEM?!
http://getbem.com/naming/

What do you think?

**Comment by amusameh** [comment]
Check this article 
https://www.smashingmagazine.com/2016/06/battling-bem-extended-edition-common-problems-and-how-to-avoid-them/

Do you think it might be overwhelming to apply BEM? 
If we are to stick with BEM I think everyone should take a good look at the docs and some example so we could make sure we are doing it right.

What do you think?
@FarahZaqout @ashatat @RamyAlshurafa

**Comment by ashatat** [comment]
@amusameh 
I read the article
it says no different than the docs
what do you mean?

**Comment by FarahZaqout** [comment]
Well, we have agreed on using BEM and should have got the hang of it by now.
