### ISSUE TITLE
Using no libraries/frameworks for the front end.

### ISSUE THREAD

**Issue by FarahZaqout** [ashatat/e-commerce#57]
Hey guys. I have been struggling a bit thinking about the components and how to architect the front end of this project. Thinking in react doesn't make that much sense to me honestly. This has nothing to do with performance, state or anything like that. It's just about my overall understanding/experience with front end overall.

I haven't worked much with HTML and CSS, and I think it is the main reason why I struggle with this. I think I need to reproduce this project's front end in pure HTML and CSS once we finish working (no handlebars either). Otherwise, I believe no matter how much time I spend reading the react docs, there would be a fundamental problem in my way of thinking. There is no way for me to know for sure, except if I try that.

I think writing each page in pure html without worrying about re-usability and architecture would allow me to do a much more thorough job diving into HTML and CSS.

Right now with react I feel like I'm trying to master express before working with nodejs, which is very stupid.

I don't know if you guys felt the same at some point and how you handled it. Any thoughts?
@ashatat @amusameh @RamyAlshurafa

**Comment by FarahZaqout** [comment]
When I'm working on something back-end, I feel like I can easily imagine everything in my mind before I even start working. In front end, I'm just stumbling into problems and solving them in a very inefficient way, and that's okay. My main problem is that I don't feel like I'm learning from my mistakes. Working with Express or mongo, with every mistake, I can immediately tell what I learned from that, and I can tell that I probably won't make that mistake again, or at least, have a very easy time solving it if I do. In react, this is not the case at all, as in, a new piece does not fall into the puzzle.

**Comment by ashatat** [comment]
maybe with CSS, I feel that still, I can't wrap my head around it.
but HTML is just a markup language if you know the basic semantic meaning of the tags
That's all of what I think HTML can give you
So if you are familiar with HTML basic stuff, then I think you're ok
and we all need to read more about CSS

@amusameh  what do you think?

**Comment by RamyAlshurafa** [comment]
I endorse what @ashatat said
